version: '3.3'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=quiz-maker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=quiz-maker
      - DB_USER=postgres
      - DB_PASSWORD=password
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
    volumes:
      - .:/app
    restart: on-failure

  metabase_db:
    image: postgres:15
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase_user
      - POSTGRES_PASSWORD=metabase_pass
    volumes:
      - metabase_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_pass
      MB_DB_HOST: metabase_db
    depends_on:
      - metabase_db
      - db
    volumes:
      - metabase_data:/metabase-data
    restart: always

volumes:
  postgres_data:
  metabase_data:
  metabase_postgres_data: